apiVersion: skaffold/v2alpha4
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: geteko/auth
      context: auth
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: geteko/client
      context: client
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: geteko/tickets
      context: tickets
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: geteko/orders
      context: orders
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: geteko/expiration
      context: expiration
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: geteko/payments
      context: payments
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
